version: '3.8'

services:
  bcg-slides-generator:
    build: .
    container_name: bcg-slides-generator
    ports:
      - "8082:8082"
    volumes:
      - ./data:/app/data:ro
      - ./output:/app/output
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bcg-network

  # Development service with hot reload
  bcg-slides-dev:
    build: .
    container_name: bcg-slides-dev
    ports:
      - "8083:8082"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["sh", "-c", "npm install && npm run dev"]
    profiles:
      - dev
    networks:
      - bcg-network

networks:
  bcg-network:
    driver: bridge

volumes:
  node_modules:

